# Generated by Django 4.0.2 on 2022-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job1',
            name='uploadimage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
