# Generated by Django 4.0.2 on 2022-06-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='dob',
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
