# Generated by Django 4.0.2 on 2022-06-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_remove_resume_dob_alter_resume_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='my_file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='resume',
            name='Address',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='DECLARATION',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='Date',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='EDUCATIONQUALIFICATION',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='HOBBIESINTEREST',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='Objective',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='PROJECTS',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='TRAININGS',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='Workexperience',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
