# Generated by Django 4.0.2 on 2022-06-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_remove_resume_my_file_remove_resume_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='sname',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
