# Generated by Django 4.0.2 on 2022-06-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_resume_sname_alter_resume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ITSKILLS',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
