# Generated by Django 4.0.2 on 2022-06-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_resume_itskills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='EDUCATIONQUALIFICATION',
            new_name='percentage',
        ),
        migrations.AddField(
            model_name='resume',
            name='Passingyear',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='branch',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='course',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
