# Generated by Django 4.0.2 on 2022-07-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
