# Generated by Django 4.0.2 on 2022-07-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_delete_image_delete_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job1',
            name='uploadimage',
        ),
    ]
